export const ExportResources = [
  { value: 'account', text: 'Accounts' },
  { value: 'item', text: 'Artículos' },
  { value: 'item_category', text: 'Categorías de artículos' },
  { value: 'customer', text: 'Customers' },
  { value: 'vendor', text: 'Vendors' },
  { value: 'manual_journal', text: 'Manual Journal' },
  { value: 'expense', text: 'Expenses' },
  { value: 'sale_invoice', text: 'Invoices' },
  { value: 'sale_estimate', text: ' Estimates' },
  { value: 'sale_receipt', text: 'Receipts' },
  { value: 'payment_receive', text: 'Payments Received' },
  { value: 'credit_note', text: 'Abonos' },
  { value: 'bill', text: 'Bills' },
  { value: 'bill_payment', text: 'Bill Payments' },
  { value: 'vendor_credit', text: 'Abonos de proveedor' },
  { value: 'tax_rate', text: 'Tipo impositivo' },
];
