import React from 'react';
import { Button, Callout, Card, Dialog, FormGroup, HTMLSelect, HTMLTable, InputGroup, Intent, Spinner, Switch, Tag } from '@blueprintjs/core';
import styled from 'styled-components';
import { AppToaster, DashboardPageContent } from '@/components';
import { useRetrySii, useSiiConfig, useSiiRecord, useSiiRecords, useSubmitSii, useSyncSii, useUpdateSiiConfig } from '@/hooks/query/sii';
import type { SiiConsoleQuery } from '@farocapital/sdk-ts';
const now=new Date(),year=now.getFullYear(); const defFrom=`${year}-01-01`,defTo=`${year}-12-31`;
const statusIntent=(s:string)=>s==='accepted'?Intent.SUCCESS:s==='rejected'||s==='failed'?Intent.DANGER:s==='accepted_with_errors'?Intent.WARNING:Intent.PRIMARY;
export function SiiConsole(){
 const [q,setQ]=React.useState<SiiConsoleQuery>({page:1,pageSize:25}); const [fromDate,setFrom]=React.useState(defFrom); const [toDate,setTo]=React.useState(defTo); const [detail,setDetail]=React.useState<number>();
 const {data:config}=useSiiConfig(); const update=useUpdateSiiConfig(); const {data,isLoading,refetch}=useSiiRecords(q); const sync=useSyncSii(); const submit=useSubmitSii(); const retry=useRetrySii();
 const act=async(fn:()=>Promise<any>,msg:string)=>{try{await fn();AppToaster.show({message:msg,intent:Intent.SUCCESS});await refetch();}catch(e:any){AppToaster.show({message:e?.message||'Operación SII no completada.',intent:Intent.DANGER});}};
 const save=(body:any)=>act(()=>update.mutateAsync(body),'Configuración SII guardada.');
 return <><DashboardPageContent><Page><Header><div><h2>SII · Suministro Inmediato de Información</h2><p>Generación, auditoría y transporte de registros SII 1.1.</p></div><Button icon="refresh" onClick={()=>refetch()}>Actualizar</Button></Header>
 <Callout intent={config?.transportReady?Intent.SUCCESS:config?.enabled?Intent.WARNING:Intent.NONE} title={config?.enabled?'SII activado':'SII desactivado'}>{config?.transportReady?'Certificado y endpoints preparados para transmisión.':config?.enabled?'Puede generar registros, pero falta completar certificado/passphrase/endpoints para transmitir.':'Al activarlo, VERI*FACTU quedará deshabilitado para esta empresa.'}{config?.warnings?.length?` Avisos: ${config.warnings.join(', ')}.`:''}</Callout>
 <Card><Grid><FormGroup label="Activación"><Switch checked={Boolean(config?.enabled)} label="Empresa acogida/obligada al SII" onChange={()=>save({enabled:!config?.enabled})}/></FormGroup><FormGroup label="Entorno"><HTMLSelect value={config?.environment||'test'} onChange={e=>save({environment:e.target.value})}><option value="test">Pruebas</option><option value="production">Producción</option></HTMLSelect></FormGroup><FormGroup label="Certificado"><div>{config?.certificateConfigured?config.certificateExists?`✓ ${config.certificateFilename||'configurado'}`:'Ruta no accesible':'No configurado'} · contraseña {config?.passphraseConfigured?'configurada':'opcional/no configurada'}</div></FormGroup><FormGroup label="Endpoint emitidas"><InputGroup defaultValue={config?.endpoints?.issued||''} placeholder="URL servicio emitidas" onBlur={e=>save({endpointIssued:e.target.value})}/></FormGroup><FormGroup label="Endpoint recibidas"><InputGroup defaultValue={config?.endpoints?.received||''} placeholder="URL servicio recibidas" onBlur={e=>save({endpointReceived:e.target.value})}/></FormGroup><FormGroup label="Endpoint cobros RECC"><InputGroup defaultValue={config?.endpoints?.issuedPayment||''} placeholder="URL cobros emitidas" onBlur={e=>save({endpointIssuedPayment:e.target.value})}/></FormGroup><FormGroup label="Endpoint pagos RECC"><InputGroup defaultValue={config?.endpoints?.receivedPayment||''} placeholder="URL pagos recibidas" onBlur={e=>save({endpointReceivedPayment:e.target.value})}/></FormGroup></Grid></Card>
 <Card><Filters><FormGroup label="Desde"><input type="date" value={fromDate} onChange={e=>setFrom(e.target.value)}/></FormGroup><FormGroup label="Hasta"><input type="date" value={toDate} onChange={e=>setTo(e.target.value)}/></FormGroup><FormGroup label="Buscar"><InputGroup placeholder="Número, tercero, NIF" value={q.search||''} onChange={e=>setQ(x=>({...x,page:1,search:e.target.value}))}/></FormGroup><FormGroup label="Estado"><HTMLSelect value={q.status||''} onChange={e=>setQ(x=>({...x,page:1,status:e.target.value||undefined}))}><option value="">Todos</option><option value="generated">Generado</option><option value="submitted">Enviado</option><option value="accepted">Aceptado</option><option value="accepted_with_errors">Aceptado con errores</option><option value="rejected">Rechazado</option><option value="failed">Fallo transporte</option></HTMLSelect></FormGroup><Button intent={Intent.PRIMARY} icon="refresh" loading={sync.isPending} onClick={()=>act(()=>sync.mutateAsync({fromDate,toDate}),'Registros SII sincronizados.')}>Generar/sincronizar</Button></Filters></Card>
 <Card>{isLoading?<Spinner/>:<TableWrap><HTMLTable striped condensed><thead><tr><th>ID</th><th>Tipo</th><th>Documento</th><th>Período</th><th>Tercero</th><th>Estado</th><th>Intentos</th><th>Acciones</th></tr></thead><tbody>{(data?.data||[]).map((r:any)=><tr key={r.id}><td>{r.id}</td><td>{r.recordKind||r.record_kind}</td><td>{r.sourceNumber||r.source_number}</td><td>{`${r.periodYear||r.period_year}/${r.periodMonth||r.period_month}`}</td><td>{r.counterpartyName||r.counterparty_name||'—'}<br/><small>{r.counterpartyTaxNumber||r.counterparty_tax_number||''}</small></td><td><Tag intent={statusIntent(r.status)}>{r.status}</Tag></td><td>{r.attempts||0}</td><td><Button small onClick={()=>setDetail(r.id)}>Ver</Button>{['generated','failed','rejected'].includes(r.status)&&<Button small intent={Intent.PRIMARY} disabled={!config?.transportReady} loading={submit.isPending||retry.isPending} onClick={()=>act(()=>r.status==='generated'?submit.mutateAsync(r.id):retry.mutateAsync(r.id),'Registro SII procesado.')}>{r.status==='generated'?'Enviar':'Reintentar'}</Button>}</td></tr>)}</tbody></HTMLTable></TableWrap>}</Card>
 </Page></DashboardPageContent><Detail id={detail} onClose={()=>setDetail(undefined)}/></>;
}
function Detail({id,onClose}:{id?:number;onClose:()=>void}){const {data,isLoading}=useSiiRecord(id);return <Dialog isOpen={Boolean(id)} onClose={onClose} title={id?`Registro SII #${id}`:'Registro SII'} style={{width:'min(1080px,94vw)'}}><div className="bp4-dialog-body">{isLoading||!data?<Spinner/>:<Details><b>Estado</b><span><Tag intent={statusIntent(data.status)}>{data.status}</Tag></span><b>SHA-256</b><code>{data.payloadSha256||data.payload_sha256||'—'}</code><b>CSV AEAT</b><span>{data.aeatCsv||data.aeat_csv||'—'}</span><b>Error</b><span>{[data.errorCode||data.error_code,data.errorMessage||data.error_message].filter(Boolean).join(' · ')||'—'}</span><b>XML</b><pre>{data.payloadXml||data.payload_xml||'—'}</pre><b>Respuesta</b><pre>{data.responseXml||data.response_xml||'—'}</pre></Details>}</div><div className="bp4-dialog-footer"><div className="bp4-dialog-footer-actions"><Button onClick={onClose}>Cerrar</Button></div></div></Dialog>}
const Page=styled.div`display:grid;gap:16px;padding-bottom:24px;`;const Header=styled.div`display:flex;justify-content:space-between;gap:16px;align-items:flex-start;`;const Grid=styled.div`display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;`;const Filters=styled.div`display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;align-items:end;`;const TableWrap=styled.div`overflow:auto;max-height:620px;`;const Details=styled.div`display:grid;grid-template-columns:150px 1fr;gap:10px;align-items:start;pre{white-space:pre-wrap;max-height:300px;overflow:auto;background:rgba(128,128,128,.08);padding:10px}code{word-break:break-all}`;
